apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue-green-app
  namespace: app
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: blue-green-app
  template:
    metadata:
      labels:
        app: blue-green-app
    spec:
      containers:
      - name: blue-green-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
                - sleep
                - "50"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      terminationGracePeriodSeconds: 40      
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 20s}
        - setWeight: 50
        - pause: {duration: 20s}
        - setWeight: 100
